/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
//import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import javax.swing.JSpinner;



/**
 *
 * @author Tony Babu
 */
public class Travel_Management extends javax.swing.JFrame {

    /**
     * Creates new form Travel_management
     */
    String first,Surname,address,postcode,Email;
    int phone;
    double rTAx,rSubTotal,rTotal;
    public Travel_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setText("    Air Line Ticket  Counter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Email");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 249, 170, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("First Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Surname");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 60));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Post Code");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 20));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, 30));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, -1));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 180, 50));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, 30));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 190, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Phone no.");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 209, 170, 20));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 340));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Accomadation");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Departure Point");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Chennai", "Bengaluru", "Delhi", "Pune", "Tirupati", "Hyderabadh", "Mumbai", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 180, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Destination");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton1.setText("Exit Luggage");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 200, 40));

        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton3.setText("Air Miles Over 2000");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 40));

        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton4.setText("Travelling Insurance Paid");
        jPanel3.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, 40));

        jRadioButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton6.setText("Airport Tax Paid");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 40));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Chennai", "Bengaluru", "Delhi", "Pune", "Tirupati", "Hyderabadh", "Mumbai", " " }));
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 180, 30));
        jPanel3.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 180, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 480, 340));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton5.setText("Airport Tax Paid");
        jPanel4.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 40));

        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton2.setText("First Class");
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 120, 40));

        jRadioButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton8.setText("Economy");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 120, 40));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setText("Ticket");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        jRadioButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton9.setText("Standard");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 40));

        jRadioButton10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton10.setText("Single");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, 40));

        jRadioButton11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton11.setText("Return");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 120, 40));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setText("Flight");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 430, 30));

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 110, 40));

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 40));

        jButton7.setText("Previous");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 420, 230));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Total");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setText("Sub Total");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("Tax");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 160, 40));

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Total");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, 40));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 230, 30));

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel5.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 230, 30));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 230, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 480, 230));

        jPanel6.setBackground(new java.awt.Color(51, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 5), "Receipt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 60, 350, 420));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 130, 40));

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("Receipt");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 130, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 380, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 //private JFrame frame;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(null,"Confirm if you want to exit","Travel Management System",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText (null);
        jTextField2.setText (null);
        jTextField3.setText (null);
        jTextField4.setText (null);
        jTextField5.setText (null); 
        jTextField7.setText (null);
        jTextField6.setText (null);
        jTextField8.setText (null);
        jTextField9.setText (null);
        //jComboBox1.setSelectedItem("None");
        jComboBox2.setSelectedItem("None");
        jRadioButton1.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton6.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton5.setSelected(false);
       // jRadioButton7.setSelected(false);
        jRadioButton8.setSelected(false);
        jRadioButton9.setSelected(false);
        jRadioButton10.setSelected(false);
        jRadioButton11.setSelected(false);
       // jRadioButton12.setSelected(false);
        jTextArea1.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed
     
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat ("HH:mm:ss"); 
        String iTime= (tTime.format (timer.getTime()));
        SimpleDateFormat Tdate = new SimpleDateFormat ("dd-MMM-yyyy");

        String iDate = (Tdate.format (timer.getTime()));
        String ref="";
        int num1 = 1325 + (int) (Math.random()*4238);
        ref += num1 + 1325;
        first =(jTextField2.getText()); 
        Surname = (jTextField3.getText());
        address = (jTextField4.getText());
        postcode = (jTextField5.getText());
        phone =Integer.parseInt(jTextField6.getText()); 
        Email = (jTextField7.getText());
        rTAx = Double.parseDouble(jTextField9.getText());
        rSubTotal = Double.parseDouble(jTextField8.getText());
        rTotal = Double.parseDouble(jTextField1.getText());
        jTextArea1.append("""
                          \tTravel Management System:
                          
                          Ref:\t\t"""+ref+"\n---------------------------------------------------------------------------"+"\nName:\t\t"+first+"\nSurname:\t\t"+Surname
                +"\nAddress:\t\t"+address+"\nPostcode:\t\t"+postcode+"\nTelephone:\t\t"+phone+"\nEmail:\t\t"+Email+"\nTax:\t\t"+rTAx
                +"\nSub Total:\t\t"+rSubTotal+"\nTotal:\t\t"+rTotal +"\n------------------------------------------------------------------\n"+"\nDate:"+iDate +" \tTime" + iTime+"\n\n\tThanks for using \n Travel Management System");
        
            Connection con = null;
            PreparedStatement ps ;
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/travel_mngt";
            String user = "root";
            String pwd = "29-05-2004";
            con = DriverManager.getConnection(url, user, pwd);
            System.out.println("Connection Established");

            //Statement st = con.createStatement();
            String q = "INSERT INTO detail (first, Surname, address, postcode, phone, Email, rTAx, rSubTotal, rTotal) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            ps = con.prepareStatement(q);
            ps.setString(1, first);
            ps.setString(2, Surname);
            ps.setString(3, address);
            ps.setString(4, postcode);
            ps.setInt(5, phone);
            ps.setString(6, Email);
            ps.setDouble(7, rTAx);
            ps.setDouble(8, rSubTotal);
            ps.setDouble(9, rTotal);

            ps.executeUpdate();
            System.out.println("Row created successfully");
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Travel_Management.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Connection closed");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed
    public void task(double accom,double plane,double ticket){
        double airportTax=6.7;
        double airMiles=85.9;
        double insurance=62.4;
        double exitLuggage=25.9;
     
double[] TravelCost=new double[20];
double iTax = 4.5;

if(jRadioButton6.isSelected()){
    TravelCost[0] =   accom + plane+ticket;
    TravelCost[1]= ((TravelCost[0]*iTax)/100);
    String Tax = String.format("%.2f", TravelCost[1]);
    jTextField9.setText((Tax));
    String subTotal = String.format("%.2f", TravelCost [0]);
    jTextField8.setText (subTotal);
    String Total = String.format("%.2f", TravelCost[0] + TravelCost[1]);
    jTextField1.setText (Total);
}
if( jRadioButton6.isSelected() && jRadioButton3.isSelected()){
    TravelCost[0] =  accom + plane+ticket+airMiles;
    TravelCost[1]= ((TravelCost[0]*iTax)/100);
    String Tax = String.format("%.2f", TravelCost[1]);
    jTextField9.setText((Tax));
    String subTotal = String.format("%.2f", TravelCost [0]);
    jTextField8.setText (subTotal);
    String Total = String.format("%.2f", TravelCost[0] + TravelCost[1]);
    jTextField1.setText (Total);
}
if( jRadioButton6.isSelected() && jRadioButton3.isSelected() && jRadioButton4.isSelected()){
    TravelCost[0] =  accom + plane+ticket+airMiles+insurance;
    TravelCost[1]= ((TravelCost[0]*iTax)/100);
    String Tax = String.format("%.2f", TravelCost[1]);
    jTextField9.setText((Tax));
    String subTotal = String.format("%.2f", TravelCost [0]);
    jTextField8.setText (subTotal);
    String Total = String.format("%.2f", TravelCost[0] + TravelCost[1]);
    jTextField1.setText (Total);
}
if(jRadioButton6.isSelected() && jRadioButton3.isSelected() && jRadioButton4.isSelected() && jRadioButton1.isSelected()){
    TravelCost[0] =  accom + plane+ticket+airportTax+airMiles+insurance+exitLuggage;
    TravelCost[1]= ((TravelCost[0]*iTax)/100);
    String Tax = String.format("%.2f", TravelCost[1]);
    jTextField9.setText((Tax));
    String subTotal = String.format("%.2f", TravelCost [0]);
    jTextField8.setText (subTotal);
    String Total = String.format("%.2f", TravelCost[0] + TravelCost[1]);
    jTextField1.setText (Total);
}
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double Bengaluru=2450;
        double Chennai=2350;
        double Mumbai=2650;
        double Tirupati=2250;
        double Pune=2550;
        double Delhi=2850;
        
        
        try{
            jSpinner1.commitEdit();
        }catch(java.text.ParseException e){}
        int value=(Integer)jSpinner1.getValue();
        if(value<0){
            value=0;
            jSpinner1.setValue(value);
        }
        
        double standardFlight=2.5;
        double economyFlight=65.5;
        double firstClass=122.5;
        
        double singleTicket=500;
        double ReturnTicket=1000;

if ((jComboBox3.getSelectedItem().equals ("Chennai")))
{
        if(jRadioButton9.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Chennai*value,standardFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Chennai*value,standardFlight,ReturnTicket);
            }
        }
        if(jRadioButton8.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Chennai*value,economyFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Chennai*value,economyFlight,ReturnTicket);
                
            }
            
        }
        if(jRadioButton2.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Chennai*value,firstClass,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Chennai*value,firstClass,ReturnTicket);
            }
        }
        
    }
if((jComboBox3.getSelectedItem().equals ("Bengaluru"))){
        if(jRadioButton9.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Bengaluru*value,standardFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Bengaluru*value,standardFlight,ReturnTicket);
            }
        }
        if(jRadioButton8.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Bengaluru*value,economyFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Bengaluru*value,economyFlight,ReturnTicket);
                
            }
            
        }
        if(jRadioButton2.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Bengaluru*value,firstClass,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Bengaluru*value,firstClass,ReturnTicket);
            }
        }
        
    
}
if ((jComboBox3.getSelectedItem().equals ("Mumbai")))
{
        if(jRadioButton9.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Mumbai*value,standardFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Mumbai*value,standardFlight,ReturnTicket);
            }
        }
        if(jRadioButton8.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Mumbai*value,economyFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Mumbai*value,economyFlight,ReturnTicket);
                
            }
            
        }
        if(jRadioButton2.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Mumbai*value,firstClass,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Mumbai*value,firstClass,ReturnTicket);
            }
        }
        
    
    }
if ((jComboBox3.getSelectedItem().equals ("Tirupati")))
{
        if(jRadioButton9.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Tirupati*value,standardFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Tirupati*value,standardFlight,ReturnTicket);
            }
        }
        if(jRadioButton8.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Tirupati*value,economyFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Tirupati*value,economyFlight,ReturnTicket);
                
            }
            
        }
        if(jRadioButton2.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Tirupati*value,firstClass,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Tirupati*value,firstClass,ReturnTicket);
            }
        }
        
    }
if ((jComboBox3.getSelectedItem().equals ("Pune")))
{
        if(jRadioButton9.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Pune*value,standardFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Pune*value,standardFlight,ReturnTicket);
            }
        }
        if(jRadioButton8.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Pune*value,economyFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Pune*value,economyFlight,ReturnTicket);
                
            }
            
        }
        if(jRadioButton2.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Pune*value,firstClass,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Pune*value,firstClass,ReturnTicket);
            }
        }
        
    
    
    }
if ((jComboBox3.getSelectedItem().equals ("Delhi")))
{
        if(jRadioButton9.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Delhi*value,standardFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Delhi*value,standardFlight,ReturnTicket);
            }
        }
        if(jRadioButton8.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Delhi*value,economyFlight,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Delhi*value,economyFlight,ReturnTicket);
                
            }
            
        }
        if(jRadioButton2.isSelected()){
            if(jRadioButton10.isSelected()){
                task(Delhi*value,firstClass,singleTicket);
            }
            if(jRadioButton11.isSelected()){
                task(Delhi*value,firstClass,ReturnTicket);
            }
        }
        
    
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DeleteFlight o=new DeleteFlight();
        o.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        frame4 o=new frame4();
        o.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travel_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travel_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travel_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travel_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travel_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
